apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.services.pylon.name }}-deployment
  labels:
    {{- include "carrier-io.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "carrier-io.specificSelectorLabels" (dict "name" "pylon" "release" .Release.Name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "carrier-io.specificSelectorLabels" (dict "name" "pylon" "release" .Release.Name) | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "carrier-io.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.services.pylon.name }}-container
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.pylon.repository }}:{{ .Values.images.pylon.tag }}"
          imagePullPolicy: {{ .Values.images.pylon.pullPolicy }}
# to be able to debug, uncomment the following lines:
#          command: ["/bin/sh","-c"]
#          args: ["python -m pylon.main || sleep infinity"]
          ports:
            - containerPort: {{ .Values.images.pylon.containerPort }}
              protocol: TCP
          volumeMounts:
            - mountPath: /data/pylon
              name: claim0
            - mountPath: /data/config
              name: config
          envFrom:
            - configMapRef:
                name: env
          env:
            - name: CORE_CONFIG_SEED
              value: "file:/data/config/pylon.yml"
# TODO
#          livenessProbe:
#            httpGet:
#              path: /
#              port: 80
#          readinessProbe:
#            httpGet:
#              path: /
#              port: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: claim0
          persistentVolumeClaim:
            claimName: {{ .Values.services.pylon.name }}-claim0
        - name: config
          configMap:
            name: {{ .Values.services.pylon.name }}-config-local
